# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PI_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('time1', models.DateTimeField(auto_now_add=True)),
                ('gener', models.BooleanField(default=False)),
            ],
        ),
    ]
