# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pi_info',
            name='gener2',
            field=models.BooleanField(default=False),
        ),
    ]
