# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pi_info_gener2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pi_info',
            old_name='gener',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='pi_info',
            name='gener2',
        ),
    ]
