# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 09:29
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160915_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_7688',
            name='age',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3),
        ),
    ]
